name: Test PR and Merge

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, closed]

jobs:
  job_1:
    runs-on: ubuntu-18.04
    
    steps:
    - name: First step
      run: echo First step executed
#     - name: Trigger error. Should fail.
#       run: exit 1
    - name: Print base ref
      run: |
        echo "Base ref is $GITHUB_BASE_REF"
    
    - name: Retrieve DS version
      if: github.base_ref == 'master' && github.event.pull_request.merged == true
      run: 
        echo ::set-env name=TAG_NAME::$(echo "0.0.2")
        
    - id: create_release
      if: github.base_ref == 'master' && github.event.pull_request.merged == true
      name: Create release on successful merge
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CI_USER_GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.TAG_NAME }}"
