name: Test PR and Merge

on:
  pull_request:
    branches: '*'

jobs:
  job_1:
    runs-on: ubuntu-18.04
    
    steps:
    - name: First step 01
      run: echo First step executed
    - name: Trigger error. Should fail.
      run: exit 1
