name: Test PR and Merge

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  job_1:
    runs-on: ubuntu-18.04
    
    steps:
    - name: First step
      run: echo First step executed
#     - name: Trigger error. Should fail.
#       run: exit 1
    
    - name: Create tag on successful merge
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: echo Create tag
