name: Test PR and Merge

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, closed]
  
  # This is for testing only.
  push:
    branches: [ test-branch ]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - name: First step
      run: echo First step executed

    - name: Print base ref
      run: |
        echo "Base ref is $GITHUB_BASE_REF"
    
    - id: checkout_ds_repo
      name: Checkout this repo
      uses: actions/checkout@v2
      
    - name: Retrieve DS version
      run: 
        echo ::set-env name=TAG_NAME::$(echo "0.0.2")
        
    - name: Check if tag name is still available.
      run: |
        DETAILS=$(git ls-remote --exit-code --tags origin "v${{ env.TAG_NAME }}" || echo "")
        if [ "$DETAILS" != "" ]; then echo "v${{ env.TAG_NAME }} tag_name is already used."; exit 1; fi
        
    - id: create_release
      if: github.base_ref == 'master' && github.event.pull_request.merged == true
      name: Create release on successful merge
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CI_USER_GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.TAG_NAME }}"
