name: Test PR and Merge

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, closed]
  
  # This is for testing only.
  push:
    branches: [ test-branch ]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - name: First step
      run: echo First step executed

    - name: Print base ref
      run: |
        echo "Base ref is $GITHUB_BASE_REF"
    
    - id: checkout_ds_repo
      name: Checkout this repo
      uses: actions/checkout@v2
      
    - name: Retrieve DS version
      run: 
        echo ::set-env name=TAG_NAME::$(echo "0.0.3")
        
    - name: Check tag name
      run: |
        EXISTS=$(git ls-remote --exit-code --tags origin "v${{ env.TAG_NAME }}" || echo "NO")
        echo ::set-env name=TAG_NAME_EXISTS::$EXISTS
      # echo "tag name exists: ${{ env.TAG_NAME_EXISTS }}"
    
    - name: tag_name available
      if: ${{ env.TAG_NAME_EXISTS }} != "NO"
      run: |
        echo "tag name exists: ${{ env.TAG_NAME_EXISTS }}"
        echo "tag name already used: v${{ env.TAG_NAME }}"
        exit 1
      #  if git ls-remote --exit-code --tags origin "v${{ env.TAG_NAME }}" >/dev/null 2>&1; then echo "Exists"; exit 1; fi
        
    - id: create_release
      if: github.base_ref == 'master' && github.event.pull_request.merged == true
      name: Create release on successful merge
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CI_USER_GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.TAG_NAME }}"
