name: Test PR and Merge

on:
  pull_request:
    types: [ready_for_review, review_requested]
  push:
    branches: [ test-branch ]

jobs:
  job_1:
    runs-on: ubuntu-18.04
    
    steps:
    - name: First step
      run: echo First step executed
