name: Test PR and Merge

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches: '*'

jobs:
  job_1:
    runs-on: ubuntu-18.04
    
    steps:
    - name: First step 02
      run: echo First step executed
    #- name: Trigger error. Should fail.
      #run: exit 1
