name: Test PR and Merge

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, closed]

jobs:
  job_1:
    runs-on: ubuntu-18.04
    
    steps:
    - name: First step
      run: echo First step executed
#     - name: Trigger error. Should fail.
#       run: exit 1
    - name: Print base ref
      run: |
        echo "Base ref is $GITHUB_BASE_REF"
    
    - name: Create tag on successful merge
      if: github.base_ref == 'master' && github.event.pull_request.merged == true
      run: echo Create tag
